apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort        # Change from ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Pod port
      nodePort: 30081   # Node port > 30000
